### ISSUE TITLE
Problem with export

### ISSUE THREAD

**Issue by maysamrasoli** [biezhi/excel-plus#30]
Hi everyone;
When i want to export a simple excel file I get this error:

`java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLStreamReader;
        at org.apache.xmlbeans.XmlBeans.buildStreamToNodeMethod(XmlBeans.java:247)
        at org.apache.xmlbeans.XmlBeans.<clinit>(XmlBeans.java:134)
        at org.apache.xmlbeans.XmlBeans.typeLoaderForClassLoader(XmlBeans.java:715)
        at org.openxmlformats.schemas.spreadsheetml.x2006.main.CTWorkbook$Factory.getTypeLoader(Unknown Source:25)
        at org.openxmlformats.schemas.spreadsheetml.x2006.main.CTWorkbook$Factory.newInstance(Unknown Source:0)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.onWorkbookCreate(XSSFWorkbook.java:460)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:263)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:257)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:245)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:243)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:213)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:188)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:274)
        at io.github.biezhi.excel.plus.writer.WriterWith2007.writeSheet(WriterWith2007.java:48)
        at io.github.biezhi.excel.plus.Writer.to(Writer.java:284)
        at io.github.biezhi.excel.plus.Writer.to(Writer.java:267)
        at tools.ActivityExcelExporter.onCreate(ActivityExcelExporter.java:34)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3095)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3258)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7058)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.xml.stream.XMLStreamReader" on path: DexPathList[[zip file "/data/app/ir.adinapp.supermarket-rusFzlLBnp2BrQKogUvP3g==/base.apk"],nativeLibraryDirectories=[/data/app/ir.adinapp.supermarket-rusFzlLBnp2BrQKogUvP3g==/lib/arm64, /system/lib64]]`

anybody can help me? tanx

**Comment by xkcoding** [comment]
it might be the poi version is not correct

is there has already existed poi dependency in your project?

**Comment by maysamrasoli** [comment]
no other dependency added.
and still the problem is not resolved.
